# Generated by Django 2.0.1 on 2018-04-04 16:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('accountType', models.IntegerField()),
                ('account', models.IntegerField()),
                ('address', models.CharField(max_length=42, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractCourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('cNo', models.IntegerField()),
                ('cName', models.CharField(max_length=40)),
                ('cCredit', models.IntegerField()),
                ('cNature', models.CharField(max_length=10)),
                ('cGrade', models.CharField(max_length=20)),
                ('cTerm', models.CharField(max_length=40)),
                ('cComposition', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ContractManagerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('mNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('tNo', models.IntegerField()),
                ('cNo', models.IntegerField()),
                ('sNo', models.IntegerField()),
                ('mark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractSelectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('cNo', models.IntegerField()),
                ('sNo', models.IntegerField()),
                ('timestamp', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ContractStudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('sNo', models.IntegerField()),
                ('sName', models.CharField(max_length=40)),
                ('sClass', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractTeacherCourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('cNo', models.IntegerField()),
                ('tNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractTeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('tNo', models.IntegerField()),
                ('tName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cNo', models.IntegerField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=40)),
                ('cCredit', models.IntegerField()),
                ('cNature', models.CharField(max_length=10)),
                ('cNumber', models.IntegerField()),
                ('cMajor', models.CharField(max_length=1000)),
                ('cGrade', models.CharField(max_length=20)),
                ('cTerm', models.CharField(max_length=40)),
                ('cComposition', models.CharField(default='期末:100%', max_length=5000)),
                ('cIntroduction', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cMaterialsHash', models.CharField(max_length=100)),
                ('cMaterialsName', models.CharField(max_length=1000)),
                ('cMaterialsType', models.CharField(max_length=10)),
                ('cMaterialsSize', models.CharField(max_length=10)),
                ('cMaterialsTime', models.DateField(auto_now=True)),
                ('cNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1017.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('uid', models.CharField(max_length=40, unique=True)),
                ('account', models.IntegerField(primary_key=True, serialize=False)),
                ('accountType', models.CharField(max_length=13)),
                ('LoginPassword', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('unlockPassword', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('mNo', models.IntegerField(primary_key=True, serialize=False)),
                ('mName', models.CharField(max_length=40)),
                ('LoginPassword', models.CharField(max_length=20)),
                ('mAddress', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('mUnlockPassword', models.CharField(blank=True, max_length=20, null=True)),
                ('mTelephone', models.CharField(blank=True, max_length=11, null=True)),
                ('mEmail', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qNo', models.IntegerField(primary_key=True, serialize=False)),
                ('qQuestion', models.CharField(max_length=5000)),
                ('qOption', models.CharField(max_length=5000)),
                ('qAnswer', models.CharField(max_length=10)),
                ('cNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1017.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sNo', models.IntegerField(primary_key=True, serialize=False)),
                ('sName', models.CharField(max_length=40)),
                ('sGender', models.CharField(max_length=10)),
                ('sClass', models.IntegerField()),
                ('sMajor', models.CharField(max_length=40)),
                ('sSchool', models.CharField(max_length=40)),
                ('sGrade', models.CharField(max_length=10)),
                ('LoginPassword', models.CharField(max_length=20)),
                ('sAddress', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('sUnlockPassword', models.CharField(blank=True, max_length=20, null=True)),
                ('sTelephone', models.IntegerField(blank=True, null=True)),
                ('sEmail', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('cNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1017.Course')),
                ('sNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1017.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tNo', models.IntegerField(primary_key=True, serialize=False)),
                ('tName', models.CharField(max_length=40)),
                ('tSchool', models.CharField(max_length=40)),
                ('LoginPassword', models.CharField(max_length=20)),
                ('tAddress', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('tUnlockPassword', models.CharField(blank=True, max_length=20, null=True)),
                ('tTelephone', models.CharField(blank=True, max_length=11, null=True)),
                ('tEmail', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sClass', models.CharField(blank=True, max_length=256, null=True)),
                ('cNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1017.Course')),
                ('tNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1017.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourseApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('cNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1017.Course')),
                ('tNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1017.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherNewCourseApply',
            fields=[
                ('ncacNo', models.IntegerField(primary_key=True, serialize=False)),
                ('ncacName', models.CharField(max_length=40)),
                ('ncacCredit', models.IntegerField()),
                ('ncacNature', models.CharField(max_length=10)),
                ('ncacNumber', models.IntegerField()),
                ('ncacMajor', models.CharField(max_length=1000)),
                ('ncacGrade', models.CharField(max_length=20)),
                ('ncacTerm', models.CharField(max_length=40)),
                ('ncacComposition', models.CharField(default='期末:100%', max_length=5000)),
                ('ncacIntroduction', models.CharField(blank=True, max_length=5000, null=True)),
                ('ncaStatus', models.CharField(max_length=10)),
                ('ncatNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1017.Teacher')),
            ],
        ),
    ]
